//! One live session's shared state.
//!
//! Every worker thread for a session -- control, receive, transmit -- holds
//! an `Arc` of this record and checks its stop flag, which is what bounds
//! shutdown to roughly one socket timeout.

use super::*;

/// Internal session bookkeeping shared with worker threads.
pub(crate) struct SessionRecord {
    pub id: SessionId,
    /// Session identifier assigned by the host and used on resume.
    pub wire_id: u64,
    pub peer: PeerInfo,
    pub roles: Roles,
    pub codec: CodecKind,
    pub format: AudioFormat,
    /// This side sends audio (peer receives).
    pub sending: bool,
    /// This side receives audio (peer sends).
    pub receiving: bool,
    pub stop: Arc<AtomicBool>,
    /// Set by `disconnect`; the control thread sends `bye` and tears down.
    pub bye_requested: AtomicBool,
    /// Identifies the control-key generation currently in use. Host-side
    /// grace waits compare generations to notice a replacement.
    pub control_generation: AtomicU64,
    /// Derived from the original PAKE shared secret. It is never transmitted
    /// and is used only for challenge-response resumption.
    pub resume_secret: [u8; 32],
    /// Credential generated by the client for the peer, or learned by the
    /// host from an authenticated enrollment message.
    pub trust_secret: Mutex<Option<[u8; 32]>>,
    /// Authenticated replacement stream for ADB-only operation. `None`
    /// means the session uses UDP audio.
    pub tcp_audio: Option<Arc<session::TcpAudioSlot>>,
    /// Interface-scoped UDP socket, replaceable after authenticated resume.
    pub udp_audio: Option<Arc<session::UdpAudioSlot>>,
    /// Current authenticated control peer address. The stable discovery
    /// address in `peer` remains the identity label; this field reports the
    /// path actually carrying the live control session.
    pub control_peer_addr: Mutex<SocketAddr>,
    /// Explicitly gates resume takeover and serializes racing attempts.
    pub control_state: Mutex<ControlState>,
    /// UDP address of the peer's audio socket.
    ///
    /// Only ever updated from a datagram that authenticated against this
    /// session's audio key. Learning it from any syntactically valid packet,
    /// as an earlier version did, let anyone who could reach the port
    /// redirect our outbound audio to themselves.
    pub peer_audio_addr: Mutex<Option<SocketAddr>>,
    /// Per-session transmit queue so one capture stream fans out to every
    /// receiving peer without competing consumers. Holds audio already
    /// converted into *this session's* negotiated format.
    pub outgoing: PcmQueue,
    /// Per-session receive queue holding audio converted into the engine's
    /// local format, ready to be mixed with the other sessions'.
    pub incoming: PcmQueue,
    /// Local-format-to-session-format conversion for the transmit path, with
    /// its reusable output buffer. One converter per session: they have
    /// independent geometries and independent interpolation state.
    pub capture_convert: Mutex<(Converter, Vec<f32>)>,
    /// Seals this session's outgoing datagrams. Shared between the transmit
    /// worker and the announce path, because a single nonce counter per key
    /// is what keeps the AEAD safe.
    pub audio_sealer: Mutex<Sealer>,
    /// Opens this session's incoming datagrams and tracks its replay window.
    pub audio_opener: Mutex<Opener>,
}

impl SessionRecord {
    /// Mark the current control owner as gone. Calling this more than once is
    /// harmless while the grace period is in progress.
    pub(crate) fn mark_control_dropped(&self) -> bool {
        let Ok(mut state) = self.control_state.lock() else {
            return false;
        };
        match *state {
            ControlState::Active => {
                let generation = self.control_generation.load(Ordering::Acquire);
                *state = ControlState::ResumeEligible { generation };
                true
            }
            ControlState::ResumeEligible { .. } => true,
            ControlState::Resuming { .. } => false,
        }
    }

    /// Claim one eligible resume generation. A session whose old control
    /// channel is active cannot be claimed, and only one challenge may be in
    /// flight at once.
    pub(crate) fn begin_resume(&self) -> Option<u64> {
        let Ok(mut state) = self.control_state.lock() else {
            return None;
        };
        let ControlState::ResumeEligible { generation } = *state else {
            return None;
        };
        let next = generation.checked_add(1)?;
        *state = ControlState::Resuming { generation: next };
        Some(next)
    }

    /// Return a failed resume attempt to the eligible state without rotating
    /// the live control generation.
    pub(crate) fn cancel_resume(&self, generation: u64) {
        if let Ok(mut state) = self.control_state.lock() {
            if *state == (ControlState::Resuming { generation }) {
                let current = self.control_generation.load(Ordering::Acquire);
                *state = ControlState::ResumeEligible {
                    generation: current,
                };
            }
        }
    }

    /// Commit a successful resume and rotate the control-key generation.
    pub(crate) fn finish_resume(&self, generation: u64) -> bool {
        let Ok(mut state) = self.control_state.lock() else {
            return false;
        };
        if *state != (ControlState::Resuming { generation }) {
            return false;
        }
        self.control_generation.store(generation, Ordering::Release);
        *state = ControlState::Active;
        true
    }

    /// End a grace period without allowing its old control watcher to tear
    /// down a session that has already been resumed. The state transition is
    /// serialized with `finish_resume`, so the watcher and the new owner
    /// cannot both decide the session's fate. An in-flight challenge remains
    /// in progress until it succeeds or cancels itself.
    pub(crate) fn expire_resume_grace(&self, generation: u64) -> ResumeGraceResult {
        let Ok(mut state) = self.control_state.lock() else {
            return ResumeGraceResult::InProgress {
                generation: self.control_generation.load(Ordering::Acquire),
            };
        };
        if self.control_generation.load(Ordering::Acquire) != generation {
            return ResumeGraceResult::Resumed;
        }
        match *state {
            ControlState::ResumeEligible {
                generation: current,
            } if current == generation => {
                *state = ControlState::Active;
                ResumeGraceResult::Expired
            }
            ControlState::Resuming { generation } => ResumeGraceResult::InProgress { generation },
            _ => ResumeGraceResult::Resumed,
        }
    }

    /// Abort a challenge that has remained in flight beyond the bounded
    /// handshake timeout. The caller will tear down the session; a successful
    /// finisher racing this method wins or loses under the same state lock.
    pub(crate) fn abort_resume(&self, generation: u64) -> bool {
        let Ok(mut state) = self.control_state.lock() else {
            return false;
        };
        if *state == (ControlState::Resuming { generation }) {
            *state = ControlState::Active;
            true
        } else {
            false
        }
    }
}
