[package]
name = "pw-graph-backend"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
[features]
default = ["in-memory"]
in-memory = []
pipewire = ["dep:pipewire"]

[dependencies]
pw-graph-core = { path = "../pw-graph-core" }
pw-graph-effects = { path = "../pw-graph-effects" }
thiserror.workspace = true
pipewire = { workspace = true, optional = true }
