[package]
name = "pw-graph-app"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
eframe.workspace = true
egui.workspace = true
pw-graph-backend = { path = "../pw-graph-backend" }
pw-graph-command = { path = "../pw-graph-command" }
pw-graph-config = { path = "../pw-graph-config" }
pw-graph-core = { path = "../pw-graph-core" }
pw-graph-patchbay = { path = "../pw-graph-patchbay" }
pw-graph-ui = { path = "../pw-graph-ui" }

